# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build .ipa for staging environment"
  lane :buildDev do
    gym(scheme: "appDev", workspace: "ambienge.xcworkspace", configuration: "Release", clean: true, output_directory: "build",export_method: "app-store")
    #increment_version_number
    #increment_build_number
  end

  desc "Build .ipa for production environment"
  lane :buildProd do
    gym(scheme: "appProd", workspace: "ambienge.xcworkspace", configuration: "Release", clean: true, output_directory: "build",export_method: "app-store")
    #increment_version_number
    #increment_build_number
  end
end
