# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_require 'dotenv'

default_platform(:android)

platform :android do

  private_lane :increment_version_code_android do
    path = '../app/build.gradle'
    regexVersionCode = /versionCode\s(\d+)/ 
    regexVersionName = /versionName\s(\"(\d+).(\d+).(\d+)-(\d+)\")/ 
    s = File.read(path)
    versionCode = s[regexVersionCode, 1].to_i
    s[regexVersionCode, 1] = (versionCode + 1).to_s
    versionName = s[regexVersionName, 5].to_i
    s[regexVersionName, 5] = (versionName + 1).to_s
    f = File.new(path, 'w')
    f.write(s)
    f.close
  end

  private_lane :productionMode do
    path = '../../version.tsx'
    regexMode = /'PROD' = ([^abc]+);/ 
    s = File.read(path)
    environment = s[regexMode, 1].to_i
    s[regexMode, 1] = "'PROD'"
    f = File.new(path, 'w')
    f.write(s)
    f.close
  end

  desc "Build .apk for staging environment"
  lane :buildDev do
    sh("npm","run","release:android:dev")
  end

  desc "Build .apk for production environment"
  lane :buildProd do
    sh("npm","run","release:android:prod")
    sh("mkdir", "-p", "fastlane/builds")
    sh("cp", "android/app/build/outputs/apk/production/release/app-production-release.apk", "fastlane/builds")
  end
end
